### ISSUE TITLE
requirements.txt vs install_requires

### ISSUE THREAD

**Issue by guettli** [nigma/django-request-id#6]
Since I was unsure, I asked the experts on the python distutils mailing list first: https://mail.python.org/pipermail/distutils-sig/2017-January/029992.html

Nevertheless I am unsure if the hint in the Quickstarts docs is a good solution:

> Include django-request-id in your requirements.txt file.

I personally don't want to edit requirements.txt by hand. Continous-Integration runs create the file, if all tests are successful.

I specifiy dependencies with install_requires in setup.py.

But maybe you see it different.

**Comment by nigma** [comment]
Both approaches are ok.

I'm using `requirements.txt` as a top-level file that lists all packages and their exact versions so that a fresh environment can be easily bootstrapped.

The `install_requires` lists package-level dependencies and often their versions are specified less strictly to avoid conflicts with other libraries that are relying on the same packages and to allow upgrades through `requirements.txt` without patching each `setup.py`.

If you have one main `setup.py` file it can play the role of a `requirements.txt` file just fine.
